### PR TITLE
Honour connect timeout while in WS handshake.

### LINKED ISSUE #64: WebSocket.connect hangs in handshake
Our network topology is as following:

client =====> ssl terminating proxy ======> server

If the server is down, the client can still connect at the socket level, because the proxy accepts the socket connection request. So the timeout provided to Websocket.connect() does not happen in SocketConnector.doConnect. The following HTTP handshake than hangs endlessly in WebSocket.shakeHands().

I would expect, that the timeout provided to WebSocket.connect() counts until the websocket connection is established.

How can we detect in the websocket library such a situation? Out application does not receive any callback via provided WebSocketAdapter.

### PR DESCRIPTION
**Pull request by eku**
Fixes #64

### CODE REVIEW

**Comment by eku** [comment]
@TakahikoKawasaki  any chance to get this merged?

**Comment by TakahikoKawasaki** [comment]
I'm sorry for having not responded to this. Give me some time to review it.

(Sorry I'm busy due to the fund-raising process of my new company, [Authlete, Inc.](https://www.authlete.com/) nv-websocket-client is just a volunteer work...)

**Comment by TakahikoKawasaki** [comment]
Well, (1) the second argument of <code>java.net.Socket.[connect](http://docs.oracle.com/javase/8/docs/api/java/net/Socket.html#connect-java.net.SocketAddress-int-)(SocketAddress endpoint, int timeout)</code> and (2) the argument of <code>java.net.Socket.[setSoTimeout](http://docs.oracle.com/javase/8/docs/api/java/net/Socket.html#setSoTimeout-int-)(int timeout)</code> seem to have different meanings. (I'm not 100% sure, though.) nv-websocket-client's <code>WebSocketFactory.[setConnectionTimeout](http://takahikokawasaki.github.io/nv-websocket-client/com/neovisionaries/ws/client/WebSocketFactory.html#setConnectionTimeout-int-)(int timeout)</code> is a method for (1).

Under the current implementation, when you want to change the value of <code>[SO_TIMEOUT](http://docs.oracle.com/javase/8/docs/api/java/net/SocketOptions.html#SO_TIMEOUT)</code>, you need to get the raw socket by <code>WebSocket.[getSocket()](http://takahikokawasaki.github.io/nv-websocket-client/com/neovisionaries/ws/client/WebSocket.html#getSocket--)</code> method and call [setSoTimeout](http://docs.oracle.com/javase/8/docs/api/java/net/Socket.html#setSoTimeout-int-)(int timeout) like below.

    WebSocket ws = ...;
    ws.getSocket().setSoTimeout(...);

**Comment by eku** [comment]
> Under the current implementation, when you want to change the value of SO_TIMEOUT, you need to get the raw socket by WebSocket.getSocket() method and call setSoTimeout(int timeout) like below.

```WebSocket.getSocket()``` calls internally ```mSocketConnector.getSocket()```, which is exactly how the socket is retrieved at the [beginning ](https://github.com/eku/nv-websocket-client/blob/8ca408c305dd5c5762ba9307b4a36711e260af30/src/main/java/com/neovisionaries/ws/client/WebSocket.java#L2969) of ```shakeHands()```. So the code does exactly what you suggested.

**Comment by TakahikoKawasaki** [comment]
In OpenJDK, which is one of Java implementations, the timeout value given to <code>java.net.Socket.connect(SocketAddress endpoint, int timeout)</code> is used to compute the value of a <code>struct timeval</code> variable which is passed to the <code>select()</code> system call. It is done in <code>Java_java_net_PlainSocketImpl_socketConnect()</code> function in <code>[PlainSocketImpl.c](http://code.metager.de/source/xref/openjdk/jdk8/jdk/src/solaris/native/java/net/PlainSocketImpl.c)</code> like below.

    fd_set wr, ex;
    struct timeval t;
    
    t.tv_sec = timeout / 1000;
    t.tv_usec = (timeout % 1000) * 1000;
    
    FD_ZERO(&wr);
    FD_SET(fd, &wr);
    FD_ZERO(&ex);
    FD_SET(fd, &ex);
    
    errno = 0;
    connect_rv = NET_Select(fd+1, 0, &wr, &ex, &t);

On the other hand, the value given to <code>java.net.Socket.setSoTimeout(int timeout)</code> is passed to <code>Java_java_net_PlainSocketImpl_socketSetOption()</code> function in <code>PlainSocketImpl.c</code>, and on Solaris and Linux, the value is simply ignored like below.

    /*
     * SO_TIMEOUT is a NOOP on Solaris/Linux
     */
    if (cmd == java_net_SocketOptions_SO_TIMEOUT) {
        return;
    }

Therefore, (1) the second argument of <code>java.net.Socket.connect(SocketAddress endpoint, int timeout)</code> and (2) the argument of <code>java.net.Socket.setSoTimeout(int timeout)</code> are different.

The intention of the implementation of (1) is apparently a **one-shot** timeout that has an effect only for the connection establishment step.

**Comment by eku** [comment]
@TakahikoKawasaki  thanks your explaining the difference and the implementation differences.

In most cases  setSoTimeout() will do what it is supposed to do. At least in our use case (Android Framework) it fixes #64. The aim of the change is not infinitely wait for the result of ```shakeHands()```.

Since the changes do not harm, I would highly appreciate if they get merged.

**Comment by TakahikoKawasaki** [comment]
I could not find the original definition of `SO_TIMEOUT` in C or C++, but at least in a certain C source file ([javanet.c#62](https://android.googlesource.com/toolchain/gcc/+/2c58169824949d3a597d9fa81931e001ef9b1bd0/gcc-4.2.1/libjava/classpath/native/jni/java-net/javanet.c#62)), `SO_TIMEOUT` is defined as an alias of `SO_RCVTIMEO`.

    #define SO_TIMEOUT SO_RCVTIMEO

I guess that `SO_RCVTIMEO` affects **every** read operation (= affects not only for the opening handshake but also all of subsequent read operations). If so, using the value specified by `WebSocketFactory.setConnectionTimeout(int)` as a value for `Socket.setSoTimeout(int)` is wrong and different from my intention.

**Pull request closed without merging**
